### ISSUE TITLE
Error when fast scroll to bottom

### ISSUE THREAD

**Issue by huydq189** [ericferreira1992/ag-virtual-scroll#15]
Hello,
Thank you for your ag-virtual-scroll package!

When using it, I had an issue: when scrolling too fast to the bottom it will have a space like this

But if I scroll slowly then everything works fine

Thank you
![BUG](https://media.giphy.com/media/yycJLBf0yAwwyidjjj/giphy.gif)

**Comment by huydq189** [comment]
![image](https://user-images.githubusercontent.com/37098778/189624331-587e4116-0b7f-477e-8b35-cd0bcc65e4c7.png)
The same as your example 2

**Comment by ericferreira1992** [comment]
Hello @huydq189, unfortunately that bad behavior can be happen. Nobody ever reported it, but it was known to me, even though it be a little dificult to simulate from manually. That problem is more critical when you are using row with diffierents height. Talking more about why it happens, it is a performance problem, because the browser can't resolve virtual rows as fast as the scrolling. 
But, I don't know, it seems that you are using reversal scrolling, right? If yes, it can be a problem, because ag-virtual-scroll is not prepared to work like that.

**Comment by duyjack** [comment]
@ericferreira1992 
I think the problem is height of items-container. 
If i disable height 100% in css of class items-container, it's works.
![Screenshot 2022-09-12 204705](https://user-images.githubusercontent.com/46467707/189671665-885731a0-ec37-4617-936c-8b7c5d767e8a.png)

**Comment by ericferreira1992** [comment]
Wow, wierd! Hahaha. I will do some tests with it. I back soon

**Comment by duyjack** [comment]
i think you should use height: 100% for horizontal scroll and width: 100% for vertical scroll

**Comment by ericferreira1992** [comment]
@duyjack I released a new version of ag-virtual-scroll with something changes, and removed `height: 100%`, because it really wasn't needed. if you want to see, the change is [here](https://github.com/ericferreira1992/ag-virtual-scroll/commit/ae9f93740145a80b2ccbf2857683bbdee2d1143c#diff-59da201946e650b5136275220f2a70bcf4e282ae5d525bfde0c2f14f2fe24014).

🚀🔆 [ag-virtual-scroll v1.5.1](https://www.npmjs.com/package/ag-virtual-scroll) (on NPM)

**Comment by ericferreira1992** [comment]
🚀🔆 [ag-virtual-scroll v1.5.2](https://www.npmjs.com/package/ag-virtual-scroll) (on NPM)
