### ISSUE TITLE
Implement scrollTo method or introduce start-index attribute

### ISSUE THREAD

**Issue by pnedkovp** [ericferreira1992/ag-virtual-scroll#19]
I tried using the package and it almost fully covers my needs. What I need more is a way to make the scroll show a particular item which is not currently visible.
Both a programatic way or a variable binding with an attribute would make sense for me.
Something like a scrollTo method or a start-index attribute which informs the scroll from which row to start. But this should be able to be changed dynamically and the scroll should be able to change the offset if the variable changes.

**Comment by pnedkovp** [comment]
I was able to make this work with changing the scrollTop property

**Comment by ericferreira1992** [comment]
@pnedkovp you were right when you said it would be fine if the `ag-virtual-scroll` have a method to navigate to specific index, but as you posted above, you can make bind from `ag-virtual-scroll` component and use the native method `scrollTop` to manipule that scroll, however I need to recomend you to use `smooth` behavior, because tou can get some problems if you don't do it. Example:

```javascript
let yourTop = 1000;
element.scrollTo({
   top: yourTop,
   behavior: 'smooth',
});
```

**Comment by pnedkovp** [comment]
Ok, thank you!
