### ISSUE TITLE
Sticky element should stick to bottom o thef list when scrolling up the list

### ISSUE THREAD

**Issue by zr87** [ericferreira1992/ag-virtual-scroll#2]

**Comment by ericferreira1992** [comment]
@zr87 The right way will should be insert a new @Input to set if the sticky will work in top or bottom. But this definition will be applied in "ag-virtual-scroll", not in each "ag-vs-item". Because will can't work with two different positions at the same time.

Just a question.
Will you need this feature or is just a improvement that you noticed  can be done?
