### ISSUE TITLE
Scroll to index or item

### ISSUE THREAD

**Issue by WilliamAndreu** [ericferreira1992/ag-virtual-scroll#25]
I think it would be a good idea to provide a function that allows scrolling to an index or item provided by the user.

**Comment by ericferreira1992** [comment]
@WilliamAndreu, I didn't reply you by that time because this feature isn't possível apply in ag-virtual-scroll yet. It's due the fact the ag-virtual-scroll can render elements/rows with different heights, which makes this virtualization impossible because its can't calculate of the `top` value given the `scrollTop` value. But I'll keep this in my mind, maybe in future we can solve this feature.
